api:
  dashboard: false
  insecure: true

entryPoints:
  web:
    address: ":18081"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":18444"

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: siteio-network

certificatesResolvers:
  letsencrypt:
    acme:
      email: undefined
      storage: /certs/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO