#!/bin/sh
set -e

# Bootstrap/refresh the superuser from env (idempotent). Creds are generated by
# the agent on first deploy and surfaced via `siteio pocket admin`.
if [ -n "$POCKET_SUPERUSER_EMAIL" ] && [ -n "$POCKET_SUPERUSER_PASSWORD" ]; then
  pocketbase superuser upsert "$POCKET_SUPERUSER_EMAIL" "$POCKET_SUPERUSER_PASSWORD" --dir=/pb-data || true
fi

exec pocketbase serve \
  --http=0.0.0.0:8090 \
  --dir=/pb-data \
  --publicDir=/pb-code/public \
  --migrationsDir=/pb-code/pb_migrations \
  --hooksDir=/pb-code/pb_hooks
